<MeuLayout>
    BoxLayout:
        id: box
        orientation: "vertical"
        spacing: "10dp"
        size: root.width, root.height

        Label:
            id: label
            text: "Resultado..."
            font_size: 45
            background_color: (0,0,1,1)

        FloatingActionButton:
            id: fbtn
            icon: "plus"
            opposite_colors: True
            elevation: 8
            md_bg_color: 1, 0, 0, 1